[profile.default]
src = 'src'
out = 'out'
test = 'src/test'
libs = ['lib', 'lib/space-v1/lib/','lib/sense-v1/node_modules/']
verbosity = 3
eth-rpc-url = "https://eth-goerli.alchemyapi.io/v2/JrCVyH87AyAZaGXaIaxhWce4x-JqR7z-"
optimizer_runs = 20
# Block mined at Wed Aug 24 2022 05:42:00 AM +UTC
fork_block_number = 7462015
remappings = [
    'ds-test/=lib/ds-test/src/',
    'sense-v1-core/=lib/sense-v1/pkg/core/src/',
    'sense-v1-utils/=lib/sense-v1/pkg/utils/src/',
    '@rari-capital/=lib/sense-v1/node_modules/@rari-capital/',
    '@openzeppelin/contracts=lib/sense-v1/node_modules/@openzeppelin/contracts',
    '@sense-finance/=lib/sense-v1/node_modules/@sense-finance/'
]
